USE [master]
GO

/****** Object:  Database [ContactosDB]    Script Date: 23/09/2019 10:01:11 p. m. ******/
CREATE DATABASE [ContactosDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ContactosDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\ContactosDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ContactosDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\ContactosDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [ContactosDB] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ContactosDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ContactosDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ContactosDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ContactosDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ContactosDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ContactosDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [ContactosDB] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [ContactosDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ContactosDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ContactosDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ContactosDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ContactosDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ContactosDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ContactosDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ContactosDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ContactosDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [ContactosDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ContactosDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ContactosDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ContactosDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ContactosDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ContactosDB] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [ContactosDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ContactosDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ContactosDB] SET  MULTI_USER 
GO

ALTER DATABASE [ContactosDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ContactosDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ContactosDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ContactosDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ContactosDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ContactosDB] SET QUERY_STORE = OFF
GO

USE [ContactosDB]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [ContactosDB] SET  READ_WRITE 
GO

